name: build-python-dist

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish package (y/n)'
        default: 'n'
  push:
    branches: [master]
#    tags: ["v*.*.*"]
#  pull_request:
#    branches: [master]

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - uses: pguyot/arm-runner-action@v2
      env:
          CIBW_BUILD: cp39-* cp310-* cp311-*
          CIBW_SKIP: "*musllinux*"
      with:
        commands: |
            apt install -y python3-pip
            cd wrappers/python3
            python3 -m pip install setuptools
            python3 setup.py install

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build sdist
      working-directory: wrappers/python
      run: python3 setup.py sdist

    - uses: actions/upload-artifact@v3
      with:
        path: wrappers/python/dist/*.tar.gz

